# Generated by Django 2.1.2 on 2019-09-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment',
            field=models.PositiveSmallIntegerField(choices=[(0, 'cash'), (1, 'credit card')], default=0, verbose_name='Payment'),
        ),
    ]
