# Generated by Django 2.1.2 on 2019-09-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20190904_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[(0, 'pending'), (1, 'confirmed'), (2, 'cancelled')], default=0, max_length=4, verbose_name='Status'),
        ),
    ]
