# Generated by Django 2.1.2 on 2019-09-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20190925_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'confirmed'), (2, 'cancelled')], default=0, verbose_name='Status'),
        ),
    ]
