# Generated by Django 2.1.2 on 2019-10-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20190925_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesbooking',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
    ]
