export const ACTION_TYPE_SERVICE_UNAVAILABLE = "ACTION_TYPE_SERVICE_UNAVAILABLE";
export const ACTION_TYPE_SERVER_ERROR = "SERVER_ERROR";
export const ACTION_TYPE_UNAUTHORIZED = "UNAUTHORIZED";
export const ACTION_TYPE_FORBIDDEN = "FORBIDDEN";
export const ACTION_TYPE_BAD = "BAD";
export const ACTION_TYPE_NOT_FOUND = "NOT_FOUND";
export const ACTION_TYPE_SUCCESS = "SUCCESS";
export const ACTION_TYPE_CREATED = "CREATED";
export const ACTION_TYPE_DELETED = "DELETED";
export const ACTION_TYPE_REMOVE = "REMOVE";
// loading screen
export const ACTION_TYPE_LOADING = "LOADING";

// auth action types
export const ACCOUNT_LOGIN = "ACCOUNT_LOGIN";
export const ACCOUNT_LOGOUT = "ACCOUNT_LOGOUT";
export const ACCOUNT_GET_USER_DETAILS='ACCOUNT.GET_USER_DETAILS';
export const ACCOUNT_COMPANY_REGISTRATION_SUCCESS='ACCOUNT.COMPANY_REGISTRATION_SUCCESS';
// employee online status
export const EMPLOYEE_ONLINE = "EMPLOYEE_ONLINE";
export const EMPLOYEE_OFFLINE = "EMPLOYEE_OFFLINE";
// widget 
export const WIDGET_GET_GLOBAL='WIDGET.GET_GLOBAL';
export const WIDGET_GET_APPOINTMENT_SCHEDULER='WIDGET.GET_APPOINTMENT_SCHEDULER';
export const WIDGET_GET_ACTIVATED_APPOINTMENT_SCHEDULER='WIDGET.GET_ACTIVATED_APPOINTMENT_SCHEDULER';
// public appointment booking
export const UPDATE_BOOKING = "UPDATE_BOOKING";
export const CLEAR_BOOKING = "CLEAR_BOOKING";